### ISSUE TITLE
ManyToMany Fields Missing

### ISSUE THREAD

**Issue by ErikUmble** [tolomea/django-data-browser#72]
I noticed that Data Browser does not currently have the option of displaying ManyToMany fields. Perhaps this functionality is ambiguous, but it seems like it could be helpful for it to display such fields by creating a row for each relationship (even if that means having duplicate rows). 
Is this something you would be interested in adding? If not, would it be helpful if I added the functionality and submitted a pull request?

**Comment by tolomea** [comment]
Many to many fields should work, they definitely work for me.
They do need to be in your admin somehow but otherwise you should be good to go.
They show up with this icon ⇶ next to them and mouse over text that says "Traversing 'To Many' links may add multiple lines per result."
Are you on the lastest version? this support was made available by default in 4.0.14.

**Comment by ErikUmble** [comment]
My apologies. I hadn't realized I was using an older version (4.0.13). I'll update now. Thanks for the quick reply.
